[package]
name = "containers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3", default-features = false }
nix = "0.22.1"
subprocess = "0.2.7"
libc = "0.2.100"
