#!/usr/bin/env sh

set -eu

. ./scripts/docker/variables

echo "Running Container $DOCKER_CONTAINER_IMAGE_NAME"

docker run --privileged --rm -it -v  "${PWD}":/usr/src/lcir "${DOCKER_CONTAINER_IMAGE_NAME}" /bin/sh
